openapi: 3.0.0
info:
  title: Xander Global Scholars API
  version: 1.0.0
  description: API documentation for Xander Global Scholars
paths:
  /api/auth/login:
    post:
      summary: Login
      description: Logs in a user and returns a token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test@example.com
                password:
                  type: string
                  example: password
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
        "401":
          description: Invalid credentials
